#!/usr/bin/env python3
# Generated by Process Automation Script Generator

def read_file(path):
    # controlled env: only allow ./data/
    if not path.startswith("./data/"):
        raise Exception("Ruta no permitida: " + path)
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def process_text(text, mode):
    if mode == "upper":
        return text.upper()
    if mode == "lower":
        return text.lower()
    if mode == "trim":
        return text.strip()
    return text

def send_email(to, subject, body):
    # MVP: mock
    print("[EMAIL MOCK]", {"to": to, "subject": subject, "body_preview": body[:120]})

def main():
    ctx = {}

    # Trigger
    ctx["fileText"] = read_file("./data/input.txt")
    ctx["fileText"] = process_text(ctx.get("fileText",""), "upper")
    send_email("test@example.com", "Hola", str(ctx.get("fileText","")))
    return ctx

if __name__ == "__main__":
    out = main()
    print("[DONE]", out)